### ISSUE TITLE
Allow level sequence camera to contain post-process materials

### ISSUE THREAD

**Issue by NikolaJov96** [ydrive/EasySynth#11]
A user might want to add a post-process material to the camera used inside the level sequence to achieve a visual effect or introduce distortions. Do not clear that material when managing renderer target post-process materials.

**Comment by noelhumane** [comment]
Hi Nikola!
This plugin is amazing! 
Do you have any update on implementing post process material?
I have big issues with anti-aliasing. Switching to different type of AA didn't help :(
I see that EasySynth is using the default render settings from UE (UMovieRenderPipelineProjectSettings): After a render with EasySynth, if I open the Movie Render Queue, I can see that in the "settings" tab , a temp file called "MoviePipelineMasterConfig_0". This temporary setting file is the default settings file used for the EasySynth render. Would it be possible for EasySynth to use a custom setting file instead of the default one? A custom settings file in which we could turn on the Anti-aliasing and the post process material?
Thanks!

Noel.

**Comment by NikolaJov96** [comment]
Hi @noelhumane,

Thanks for reaching out! 
This feature was not needed until now, so it was not prioritized.
I'll try to look into your issues as soon as possible.

Nikola
